version: "3"

services:
  redis:
    image: "redis:6.2.1-alpine"
    ports:
      - 6379

  app:
    environment:
      PORT: 8080
      REDIS_HOST_ARG: redis
    build:
      context: .
    depends_on:
      - redis
    ports:
      - 18080:8080